### PR TITLE
Travis fix

### LINKED ISSUE #19: Set up Travis CI
- [ ] Set up CI using Travis
  - a build should be created when a commit is merged to master and when a PR is submitted
  - here's the project: https://travis-ci.org/Kentico/KenticoCloudDeliveryJavaRxSDK/
- [ ] [Protect the master branch](https://github.com/Kentico/KenticoCloudDeliveryJavaRxSDK/settings/branches/master)
- [ ] Add a badge to README
- [ ] Add a sample unit test
- [ ] Run the tests as a part of the build

Resources:
- https://docs.travis-ci.com/user/languages/android/
- https://github.com/andrewhr/rxjava-android-example/blob/master/.travis.yml

### PR DESCRIPTION
**Pull request by cunhazera**
### Motivation

Fixes #19

### Checklist

- [x] Set up CI using Travis
  - a build should be created when a commit is merged to master and when a PR is submitted
  - here's the project: https://travis-ci.org/Kentico/KenticoCloudDeliveryJavaRxSDK/
- [ ] [Protect the master branch](https://github.com/Kentico/KenticoCloudDeliveryJavaRxSDK/settings/branches/master) the repo's owner must do that, isn't it?
- [x] Add a badge to README
- [ ] Add a sample unit test
- [x] Run the tests as a part of the build, but the tests are failing. Shouldn't the test writer take a look at it?

### CODE REVIEW

**Comment by petrsvihlik** [comment]
Hi @cunhazera , the build is still [failing](https://travis-ci.org/Kentico/KenticoCloudDeliveryJavaRxSDK/builds/428461134?utm_source=github_status&utm_medium=notification) causing the status check to fail:
image

 Could you please make the build succeed?

**Comment by cunhazera** [comment]
@petrsvihlik the build is failing locally also. What command should I use to run locally?

**Comment by petrsvihlik** [comment]
@kentico-timothyf could you please help @cunhazera to spin it up locally? thx

**Comment by Neytus** [comment]
Hi @cunhazera, thank you for your effort to contribute. I have looked up logs from your failing builds - there are 2 tests that caused errors. I have temporarily disabled them, but the build unfortunately still [did not pass](https://travis-ci.org/Kentico/KenticoCloudDeliveryJavaRxSDK/builds/430573229). 

Afterward, I have made Android lint ignore errors in 2 modules and that was sufficient for the Travis build to pass. 

Both of those fixes are not the best practices though. If you want to, you can definitely look up how to solve the second one at least. 
I will try to fix the disabled tests such that they will pass and not cause errors anymore.

**Pull request merged**
